"use client";

import { CirclePause, LoaderCircle, Printer, RotateCcw, Trash2 } from "lucide-react";

interface CheckoutFooterProps { canComplete: boolean; canPrint: boolean; cartEmpty: boolean; hasHeldOrder: boolean; pending: boolean; onClear: () => void; onComplete: () => void; onHold: () => void; onPrint: () => void; onResume: () => void; }

export function CheckoutFooter({ canComplete, canPrint, cartEmpty, hasHeldOrder, pending, onClear, onComplete, onHold, onPrint, onResume }: CheckoutFooterProps) {
  return <footer className="space-y-2 border-t border-border pt-3"><div className="grid grid-cols-3 gap-2"><button className="flex min-h-11 items-center justify-center gap-1 rounded-xl border border-border text-[0.68rem] font-black text-muted-foreground transition hover:bg-destructive/8 hover:text-destructive focus-visible:ring-2 focus-visible:ring-destructive disabled:opacity-40" disabled={cartEmpty || pending} onClick={onClear} type="button"><Trash2 aria-hidden="true" className="size-4" />Clear</button><button className="flex min-h-11 items-center justify-center gap-1 rounded-xl border border-border text-[0.68rem] font-black text-muted-foreground transition hover:border-primary hover:bg-muted hover:text-secondary focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-40" disabled={cartEmpty || hasHeldOrder || pending} onClick={onHold} type="button"><CirclePause aria-hidden="true" className="size-4" />Hold</button><button className="flex min-h-11 items-center justify-center gap-1 rounded-xl border border-border text-[0.68rem] font-black text-muted-foreground transition hover:border-primary hover:bg-muted hover:text-secondary focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-40" disabled={!hasHeldOrder || !cartEmpty || pending} onClick={onResume} type="button"><RotateCcw aria-hidden="true" className="size-4" />Resume</button></div><button className="flex min-h-14 w-full items-center justify-center gap-2 rounded-xl bg-primary text-base font-black text-secondary shadow-[0_10px_25px_rgba(244,180,0,0.24)] transition hover:bg-amber-500 active:scale-[0.99] focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:bg-stone-200 disabled:text-stone-500" disabled={!canComplete || pending} onClick={onComplete} type="button">{pending && <LoaderCircle aria-hidden="true" className="size-5 animate-spin" />}{pending ? "Completing Order…" : "Complete Order"}</button><button className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-secondary/20 bg-white text-xs font-black text-secondary transition hover:bg-muted focus-visible:ring-2 focus-visible:ring-primary disabled:cursor-not-allowed disabled:opacity-45" disabled={!canPrint} onClick={onPrint} type="button"><Printer aria-hidden="true" className="size-4" />Print Last Receipt</button></footer>;
}
