import Link from "next/link";
import { notFound } from "next/navigation";

import { CashClosingPrintButton } from "@/components/cash-closing/CashClosingPrintButton";
import { getCashSession } from "@/features/cash-closing/services/cash-session-service";
import { cashSessionIdSchema } from "@/features/cash-closing/validations/cash-session-schema";
import { formatDashboardMoney } from "@/features/dashboard/formatters";
import { CASH_SESSION_MANAGEMENT_ROLES } from "@/features/cash-closing/types";
import type { UserRole } from "@/generated/prisma/client";
import { requireRole } from "@/lib/auth-utils";

export default async function CashClosingReport({ params }: { params: Promise<{ id: string }> }) {
  const [, routeParams] = await Promise.all([requireRole(CASH_SESSION_MANAGEMENT_ROLES as readonly UserRole[]), params]);
  const parsed = cashSessionIdSchema.safeParse(routeParams.id);
  if (!parsed.success) notFound();
  const session = await getCashSession(parsed.data);
  if (!session) notFound();
  const durationMinutes = Math.max(0, Math.floor(((session.closedAt ? new Date(session.closedAt) : new Date()).getTime() - new Date(session.openedAt).getTime()) / 60_000));
  const rows: Array<[string, string | null]> = [
    ["Opening cash", session.openingCash], ["Cash sales", session.cashSales], ["Card sales", session.cardSales],
    ["QR sales", session.qrSales], ["Total sales", session.totalSales], ["Cash expenses", session.cashExpenses],
    ["Total expenses", session.totalExpenses], ["Expected cash", session.expectedCash], ["Actual cash", session.actualCash],
    ["Cash difference", session.cashDifference],
  ];
  return <div className="space-y-4 pb-8">
    <div className="no-print flex justify-between"><Link className="font-bold" href="/cash-closing/history">← History</Link><CashClosingPrintButton /></div>
    <article className="cash-closing-report mx-auto max-w-3xl rounded-2xl border border-border bg-card p-6 shadow-sm print:border-0 print:shadow-none">
      <header className="border-b border-dashed border-black pb-4 text-center"><h1 className="text-2xl font-black">Rice &amp; Kottu Hut</h1><p>No.32, Padukka Road, Meegoda</p><p>0777250493 / 0778375427</p><h2 className="mt-3 font-black uppercase">Daily Cash Closing Report</h2></header>
      <dl className="grid grid-cols-2 gap-3 border-b border-dashed border-black py-4 text-sm">
        <div><dt>Session ID</dt><dd className="font-bold">{session.id}</dd></div><div><dt>Status</dt><dd className="font-bold">{session.status}</dd></div>
        <div><dt>Opened</dt><dd>{new Date(session.openedAt).toLocaleString("en-LK")}</dd></div><div><dt>Closed</dt><dd>{session.closedAt ? new Date(session.closedAt).toLocaleString("en-LK") : "Still open"}</dd></div>
        <div><dt>Opened by</dt><dd>{session.openedBy}</dd></div><div><dt>Closed by</dt><dd>{session.closedBy ?? "—"}</dd></div>
        <div><dt>Duration</dt><dd>{Math.floor(durationMinutes / 60)}h {durationMinutes % 60}m</dd></div><div><dt>Difference status</dt><dd>{session.differenceStatus ?? "Pending"}</dd></div>
      </dl>
      <dl className="py-4">{rows.map(([label, value]) => <div className="flex justify-between border-b border-dotted py-2" key={label}><dt>{label}</dt><dd className="font-bold">{value === null ? "—" : formatDashboardMoney(value)}</dd></div>)}</dl>
      {(session.openingNote || session.notes) && <section className="border-t border-dashed border-black py-4 text-sm"><p><b>Opening note:</b> {session.openingNote ?? "—"}</p><p><b>Closing note:</b> {session.notes ?? "—"}</p></section>}
      <footer className="border-t border-dashed border-black pt-5 text-center text-sm"><p className="font-bold">Generated by Startek Restaurant POS</p><p className="mt-2"><b>Startek (PVT) LTD</b></p></footer>
    </article>
  </div>;
}
