"use client";

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import type { ChartPoint, NamedChartPoint } from "@/features/reports/types";

const colors = ["#F4B400", "#4A2310", "#F97316", "#22C55E", "#EF4444", "#8B5CF6"];
const tooltipStyle = { border: "1px solid #f0dfbd", borderRadius: "12px", boxShadow: "0 10px 30px rgba(74,35,16,0.12)", fontSize: "12px" };
const formatReportMoney = (value: string | number) => `Rs. ${Number(value).toLocaleString("en-LK", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function ReportTrendChart({ data, description, title, valueType = "money" }: { data: ChartPoint[]; description: string; title: string; valueType?: "money" | "count" }) {
  const chartData = data.map((point) => ({ ...point, numericValue: Number(point.value) }));
  return <article className="report-chart rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="font-black text-secondary">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p><p className="sr-only">{data.length ? data.map((point) => `${point.label}: ${valueType === "money" ? formatReportMoney(point.value) : point.value}`).join("; ") : "No data for the selected period."}</p><div aria-label={`${title}. ${description}`} className="mt-4 h-72 w-full" role="img">{chartData.length ? <ResponsiveContainer height="100%" width="100%"><AreaChart data={chartData} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><CartesianGrid stroke="#f4ead4" strokeDasharray="3 3" vertical={false} /><XAxis axisLine={false} dataKey="label" fontSize={10} minTickGap={24} tickLine={false} /><YAxis axisLine={false} fontSize={10} tickFormatter={(value) => valueType === "money" ? `${Number(value) / 1000}k` : String(value)} tickLine={false} width={42} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [valueType === "money" ? formatReportMoney(Number(value)) : String(value), title]} /><Area dataKey="numericValue" fill="#F4B40033" stroke="#F4B400" strokeWidth={3} type="monotone" /></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center rounded-xl bg-muted/40 text-sm font-bold text-muted-foreground">No chart data</div>}</div></article>;
}

export function ReportBarChart({ data, description, title, valueType = "money" }: { data: Array<ChartPoint | NamedChartPoint>; description: string; title: string; valueType?: "money" | "count" }) {
  const chartData = data.map((point) => ({ label: "label" in point ? point.label : point.name, numericValue: Number(point.value) }));
  return <article className="report-chart rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="font-black text-secondary">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p><p className="sr-only">{chartData.length ? chartData.map((point) => `${point.label}: ${valueType === "money" ? formatReportMoney(point.numericValue) : point.numericValue}`).join("; ") : "No data for the selected period."}</p><div aria-label={`${title}. ${description}`} className="mt-4 h-72 w-full" role="img">{chartData.length ? <ResponsiveContainer height="100%" width="100%"><BarChart data={chartData} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><CartesianGrid stroke="#f4ead4" strokeDasharray="3 3" vertical={false} /><XAxis axisLine={false} dataKey="label" fontSize={10} minTickGap={18} tickLine={false} /><YAxis axisLine={false} fontSize={10} tickFormatter={(value) => valueType === "money" ? `${Number(value) / 1000}k` : String(value)} tickLine={false} width={42} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [valueType === "money" ? formatReportMoney(Number(value)) : String(value), title]} /><Bar dataKey="numericValue" fill="#F4B400" radius={[7, 7, 0, 0]} /></BarChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center rounded-xl bg-muted/40 text-sm font-bold text-muted-foreground">No chart data</div>}</div></article>;
}

export function ReportPieChart({ data, description, title }: { data: NamedChartPoint[]; description: string; title: string }) {
  const chartData = data.map((point) => ({ ...point, numericValue: Number(point.value) }));
  return <article className="report-chart rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="font-black text-secondary">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p><p className="sr-only">{chartData.length ? chartData.map((point) => `${point.name}: ${formatReportMoney(point.numericValue)}${point.count !== undefined ? ` from ${point.count} records` : ""}`).join("; ") : "No data for the selected period."}</p><div aria-label={`${title}. ${description}`} className="mt-4 h-72 w-full" role="img">{chartData.some((item) => item.numericValue > 0) ? <ResponsiveContainer height="100%" width="100%"><PieChart><Pie data={chartData} dataKey="numericValue" innerRadius={54} nameKey="name" outerRadius={88} paddingAngle={3} stroke="none">{chartData.map((entry, index) => <Cell fill={colors[index % colors.length]} key={entry.name} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(value) => [formatReportMoney(Number(value)), "Revenue"]} /><Legend iconSize={9} iconType="circle" wrapperStyle={{ fontSize: "11px" }} /></PieChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center rounded-xl bg-muted/40 text-sm font-bold text-muted-foreground">No chart data</div>}</div></article>;
}
