import { Filter, Search, X } from "lucide-react";
import Link from "next/link";

import { EXPENSE_CATEGORIES, EXPENSE_CATEGORY_LABELS } from "@/features/expenses/types";
import { APPROVED_REPORT_ORDER_STATUSES, APPROVED_REPORT_ORDER_TYPES, APPROVED_REPORT_PAYMENT_METHODS, type ReportFilterOptions, type ReportFilters } from "@/features/reports/types";

const inputClass = "h-11 w-full rounded-xl border border-input bg-white px-3 text-sm font-semibold text-secondary outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";

type FilterFlags = { search?: boolean; cashier?: boolean; orderType?: boolean; paymentMethod?: boolean; status?: boolean; category?: boolean; menuItem?: boolean; expenseCategory?: boolean };

export function ReportFilters({ error, filters, flags = {}, options, route }: { error?: string; filters: ReportFilters; flags?: FilterFlags; options: ReportFilterOptions; route: string }) {
  return <form className="no-print rounded-2xl border border-border bg-card p-4 shadow-sm" method="get"><div className="mb-4 flex items-center gap-2"><Filter aria-hidden="true" className="size-4.5 text-primary" /><h2 className="font-black text-secondary">Report filters</h2></div>{error && <p className="mb-4 rounded-xl border border-destructive/20 bg-destructive/8 px-4 py-3 text-sm font-semibold text-red-700" role="alert">{error} Showing this month instead.</p>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-8">
    <label><span className="sr-only">Date preset</span><select className={inputClass} defaultValue={filters.preset} name="preset"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="this-week">This week</option><option value="this-month">This month</option><option value="last-month">Last month</option><option value="this-year">This year</option><option value="custom">Custom range</option></select></label>
    <label><span className="mb-1 block text-[0.65rem] font-black uppercase text-muted-foreground">Custom start</span><input className={inputClass} defaultValue={filters.startDate} name="startDate" type="date" /></label>
    <label><span className="mb-1 block text-[0.65rem] font-black uppercase text-muted-foreground">Custom end</span><input className={inputClass} defaultValue={filters.endDate} name="endDate" type="date" /></label>
    {flags.search && <label className="relative sm:col-span-2"><span className="sr-only">Search report</span><Search aria-hidden="true" className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input className={`${inputClass} pl-10`} defaultValue={filters.query} maxLength={100} name="query" placeholder="Search report…" type="search" /></label>}
    {flags.cashier && <label><span className="sr-only">Cashier</span><select className={inputClass} defaultValue={filters.cashierId ?? ""} name="cashierId"><option value="">All cashiers</option>{options.cashiers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    {flags.orderType && <label><span className="sr-only">Order type</span><select className={inputClass} defaultValue={filters.orderType ?? ""} name="orderType"><option value="">All order types</option>{APPROVED_REPORT_ORDER_TYPES.map((item) => <option key={item} value={item}>{item.replaceAll("_", "-")}</option>)}</select></label>}
    {flags.paymentMethod && <label><span className="sr-only">Payment method</span><select className={inputClass} defaultValue={filters.paymentMethod ?? ""} name="paymentMethod"><option value="">All payment methods</option>{APPROVED_REPORT_PAYMENT_METHODS.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>}
    {flags.status && <label><span className="sr-only">Order status</span><select className={inputClass} defaultValue={filters.status ?? ""} name="status"><option value="">All statuses</option>{APPROVED_REPORT_ORDER_STATUSES.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>}
    {flags.category && <label><span className="sr-only">Menu category</span><select className={inputClass} defaultValue={filters.categoryId ?? ""} name="categoryId"><option value="">All categories</option>{options.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    {flags.menuItem && <label><span className="sr-only">Menu item</span><select className={inputClass} defaultValue={filters.menuItemId ?? ""} name="menuItemId"><option value="">All menu items</option>{options.menuItems.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    {flags.expenseCategory && <label><span className="sr-only">Expense category</span><select className={inputClass} defaultValue={filters.expenseCategory ?? ""} name="expenseCategory"><option value="">All expense categories</option>{EXPENSE_CATEGORIES.map((item) => <option key={item} value={item}>{EXPENSE_CATEGORY_LABELS[item]}</option>)}</select></label>}
    <label><span className="sr-only">Sort report</span><select className={inputClass} defaultValue={filters.sort} name="sort"><option value="newest">Newest / Highest</option><option value="oldest">Oldest / A–Z</option><option value="amount-high">Highest amount</option><option value="amount-low">Lowest amount</option><option value="quantity-high">Highest quantity</option></select></label>
    <label><span className="sr-only">Rows per page</span><select className={inputClass} defaultValue={filters.pageSize} name="pageSize"><option value="10">10 per page</option><option value="20">20 per page</option><option value="50">50 per page</option></select></label>
    <div className="flex gap-2 sm:col-span-2"><button className="flex h-11 flex-1 items-center justify-center rounded-xl bg-secondary px-4 text-sm font-black text-white transition hover:bg-secondary/90 focus-visible:ring-2 focus-visible:ring-primary" type="submit">Apply filters</button><Link aria-label="Clear report filters" className="flex size-11 items-center justify-center rounded-xl border border-border text-muted-foreground transition hover:border-primary hover:bg-muted focus-visible:ring-2 focus-visible:ring-primary" href={route}><X aria-hidden="true" className="size-4.5" /></Link></div>
  </div></form>;
}
