"use client";

import { Eye, KeyRound, Pencil, Power } from "lucide-react";
import Link from "next/link";

import { canManageStaff } from "@/features/staff/permissions/staff-permissions";
import type { StaffRecord } from "@/features/staff/types";
import type { UserRole } from "@/generated/prisma/client";

import { StaffRoleBadge, StaffStatusBadge } from "./staff-badges";

function dateTime(value: string | null) {
  return value ? new Date(value).toLocaleString("en-LK", { timeZone: "Asia/Colombo", dateStyle: "medium", timeStyle: "short" }) : "Never";
}

export function StaffTable({ actorId, actorRole, onEdit, onReset, onStatus, staff }: { actorId: string; actorRole: UserRole; onEdit: (staff: StaffRecord) => void; onReset: (staff: StaffRecord) => void; onStatus: (staff: StaffRecord) => void; staff: StaffRecord[] }) {
  if (!staff.length) return <section className="rounded-2xl border border-dashed border-input bg-card px-5 py-16 text-center"><h2 className="text-lg font-black text-secondary">No staff accounts found</h2><p className="mt-1 text-sm text-muted-foreground">Create the first account or change the current search filters.</p></section>;
  const iconButton = "flex size-9 items-center justify-center rounded-xl border border-border text-muted-foreground transition hover:border-primary hover:bg-muted hover:text-secondary focus-visible:ring-2 focus-visible:ring-primary";
  const actions = (item: StaffRecord) => {
    const manageable = canManageStaff(actorRole, item.role);
    return <div className="flex items-center justify-end gap-1.5"><Link aria-label={`View ${item.fullName}`} className={iconButton} href={`/staff/${item.id}`}><Eye aria-hidden="true" className="size-4" /></Link>{manageable && <><button aria-label={`Edit ${item.fullName}`} className={iconButton} onClick={() => onEdit(item)} type="button"><Pencil aria-hidden="true" className="size-4" /></button><button aria-label={`Reset password for ${item.fullName}`} className={iconButton} onClick={() => onReset(item)} type="button"><KeyRound aria-hidden="true" className="size-4" /></button>{item.id !== actorId && <button aria-label={`${item.status === "ACTIVE" ? "Deactivate" : "Activate"} ${item.fullName}`} className={`${iconButton} ${item.status === "ACTIVE" ? "hover:border-destructive/30 hover:text-destructive" : "hover:border-green-300 hover:text-green-700"}`} onClick={() => onStatus(item)} type="button"><Power aria-hidden="true" className="size-4" /></button>}</>}</div>;
  };
  return <section aria-label="Staff accounts" className="overflow-hidden rounded-2xl border border-border bg-card shadow-[0_10px_32px_rgba(74,35,16,0.07)]"><div className="divide-y divide-border lg:hidden">{staff.map((item) => <article className="space-y-3 p-4" key={item.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-black text-secondary">{item.fullName}</p><p className="truncate text-xs text-muted-foreground">@{item.username}</p></div><StaffStatusBadge status={item.status} /></div><div className="flex flex-wrap gap-2"><StaffRoleBadge role={item.role} /></div><dl className="grid grid-cols-2 gap-3 text-xs"><div className="min-w-0"><dt className="text-muted-foreground">Email</dt><dd className="truncate font-bold text-secondary">{item.email || "—"}</dd></div><div className="min-w-0"><dt className="text-muted-foreground">Phone</dt><dd className="truncate font-bold text-secondary">{item.phone || "—"}</dd></div><div><dt className="text-muted-foreground">Last login</dt><dd className="font-bold text-secondary">{dateTime(item.lastLogin)}</dd></div><div><dt className="text-muted-foreground">Created</dt><dd className="font-bold text-secondary">{dateTime(item.createdAt)}</dd></div></dl><div className="border-t border-border pt-3">{actions(item)}</div></article>)}</div><div className="hidden overflow-x-auto lg:block dashboard-scrollbar"><table className="w-full min-w-[1180px] border-collapse text-left"><caption className="sr-only">Staff accounts and administrative actions</caption><thead className="bg-secondary text-[0.65rem] uppercase tracking-wider text-white/70"><tr>{["Full Name", "Username", "Email", "Phone", "Role", "Status", "Last Login", "Created Date", "Actions"].map((heading) => <th className={`px-4 py-3.5 font-black ${heading === "Actions" ? "text-right" : ""}`} key={heading} scope="col">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{staff.map((item) => <tr className="transition hover:bg-muted/35" key={item.id}><td className="px-4 py-4 font-black text-secondary">{item.fullName}</td><td className="px-4 py-4 text-sm font-semibold text-secondary">{item.username}</td><td className="max-w-56 truncate px-4 py-4 text-sm text-muted-foreground">{item.email || "—"}</td><td className="whitespace-nowrap px-4 py-4 text-sm text-muted-foreground">{item.phone || "—"}</td><td className="px-4 py-4"><StaffRoleBadge role={item.role} /></td><td className="px-4 py-4"><StaffStatusBadge status={item.status} /></td><td className="whitespace-nowrap px-4 py-4 text-xs font-semibold text-muted-foreground">{dateTime(item.lastLogin)}</td><td className="whitespace-nowrap px-4 py-4 text-xs font-semibold text-muted-foreground">{dateTime(item.createdAt)}</td><td className="px-4 py-4">{actions(item)}</td></tr>)}</tbody></table></div></section>;
}
