ALTER TABLE "SystemSetting"
ADD COLUMN "printerMode" VARCHAR(24) NOT NULL DEFAULT 'BROWSER',
ADD COLUMN "printerAutomaticCut" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "printerDrawerOpenMode" VARCHAR(16) NOT NULL DEFAULT 'CASH_ONLY',
ADD COLUMN "printerDrawerPin" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "printerDrawerPulseOnMs" INTEGER NOT NULL DEFAULT 120,
ADD COLUMN "printerDrawerPulseOffMs" INTEGER NOT NULL DEFAULT 240;
