import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { ReportNavigation } from "@/components/reports/ReportNavigation";
import { REPORT_ACCESS_ROLES } from "@/features/reports/types";
import type { UserRole } from "@/generated/prisma/client";
import { requireRole } from "@/lib/auth-utils";

export default async function ReportsLayout({ children }: { children: React.ReactNode }) {
  const session = await requireRole(REPORT_ACCESS_ROLES as readonly UserRole[]);
  return <DashboardShell user={{ fullName: session.user.name ?? session.user.username, role: session.user.role }}><div className="report-page space-y-5 pb-8"><ReportNavigation />{children}<footer className="report-print-footer hidden">Generated by Startek Restaurant POS</footer></div></DashboardShell>;
}
