-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN     "addressLine1" TEXT NOT NULL DEFAULT 'No.32, Padukka Road',
ADD COLUMN     "addressLine2" TEXT,
ADD COLUMN     "businessRegistrationNumber" TEXT,
ADD COLUMN     "city" TEXT NOT NULL DEFAULT 'Meegoda',
ADD COLUMN     "language" TEXT NOT NULL DEFAULT 'en',
ADD COLUMN     "phone2" TEXT,
ADD COLUMN     "timezone" TEXT NOT NULL DEFAULT 'Asia/Colombo';

-- AlterTable
ALTER TABLE "SystemSetting" ADD COLUMN     "activityLoggingEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowCard" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowCash" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowNegativeBalance" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowQr" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "applicationName" TEXT NOT NULL DEFAULT 'Startek Restaurant POS',
ADD COLUMN     "applicationVersion" VARCHAR(32) NOT NULL DEFAULT '1.0.0',
ADD COLUMN     "currencySymbol" VARCHAR(8) NOT NULL DEFAULT 'Rs.',
ADD COLUMN     "dateFormat" VARCHAR(16) NOT NULL DEFAULT 'DD/MM/YYYY',
ADD COLUMN     "defaultOrderType" "OrderType" NOT NULL DEFAULT 'TAKEAWAY',
ADD COLUMN     "discountEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "invoiceNumberPadding" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "invoicePrefix" VARCHAR(8) NOT NULL DEFAULT 'RKH',
ADD COLUMN     "itemsPerPage" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maximumFixedDiscount" DECIMAL(12,2) NOT NULL DEFAULT 100000,
ADD COLUMN     "maximumPercentageDiscount" DECIMAL(5,2) NOT NULL DEFAULT 100,
ADD COLUMN     "printerHeadersFootersReminder" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "printerMargin" VARCHAR(12) NOT NULL DEFAULT 'NONE',
ADD COLUMN     "printerNotes" TEXT,
ADD COLUMN     "printerScale" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "receiptFooterText" TEXT,
ADD COLUMN     "receiptHeaderMessage" TEXT,
ADD COLUMN     "receiptShowBalance" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowCashReceived" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowCashier" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowDiscountWhenZero" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receiptShowOrderType" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowRestaurantPhone" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowServiceWhenZero" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receiptShowTaxWhenZero" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receiptVisitAgainMessage" TEXT NOT NULL DEFAULT 'Please Visit Again',
ADD COLUMN     "requireOrderNotes" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serviceChargeEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "taxEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "theme" VARCHAR(16) NOT NULL DEFAULT 'light',
ADD COLUMN     "timeFormat" VARCHAR(16) NOT NULL DEFAULT '12-hour',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
